### ISSUE TITLE
Worldwide endpoint with double colon in parameter names

### ISSUE THREAD

**Issue by jhoelzl** [azwyane/apicovid2019#2]
![endpoint_double_colon](https://user-images.githubusercontent.com/638936/80275907-e9b77000-86e4-11ea-82cc-af4756263dd8.jpg)

**Comment by jhoelzl** [comment]
In addition, for the values, `strip()` would be nice to get rid of the whitespace.

**Comment by azwyane** [comment]
Thank you so much jhoelzl for your review, I have resolved the issue. If you have any more ideas/features to add you can contact me here.
