### ISSUE TITLE
Column Order changed on source site

### ISSUE THREAD

**Issue by jhoelzl** [azwyane/apicovid2019#4]
Apparently, on https://www.worldometers.info/coronavirus the column order changed, therefore now almost all parameters in https://apicovid2019.azurewebsites.net/ have wrong values.

**Comment by azwyane** [comment]
Thank you jhoelzl for pointing out the issue. Well I found not all parameters, but only the global one had value shifted by one well countrywise and continentwise data were not affected. For now I have hardcoded but would make dynamic and flexible to changes.

**Comment by jhoelzl** [comment]
Again, in the countries, the columns are mixed. These parameters do not return the same values as in https://www.worldometers.info/coronavirus/:

* ActiveCases
* Serious
* Deaths/1Mpop

In addition, if you look e.g. on "Austria", you will find it twice in the JSON response of the api. One entry is from the table, the other one is from the section "Latest News", which is only a changelog and should not be parsed into this API.

**Comment by azwyane** [comment]
Thank you Jhoelzl for pointing out that issue. Worldometers is regularly changing its diplay format to ease the data visualization. The second value appeared to come from the yesterday's data column in the worldometers site and about active cases the value seems to appear correctly but i am in a process to figure out why the data in worldometers is differing though html scrap is working as defined.
