### ISSUE TITLE
https://apicovid2019.azurewebsites.net is down

### ISSUE THREAD

**Issue by jhoelzl** [azwyane/apicovid2019#5]
Azure Webapp Application Error

**Comment by azwyane** [comment]
sorry for the inconvenience, the application has been down by the azure website i have to look into it why it occured so suddenly, but as a measure as an alternative for now heroku instance given by [apicovid](https://apicovid2019.herokuapp.com) can be used

**Comment by azwyane** [comment]
till now it seems like my .edu subscription has expired, i had my final years time remain but as due to the covid19 my entire year remainings may have been ended. But still i  am looking forward to do every possible methods, to get the azure site back online

**Comment by azwyane** [comment]
okay the whole problem was with the azure itself, i have redeployed site as https://apicovid2019test.azurewebsites.net/ 
now new url has name as apicovid2019test , all you have to is replace the url with this https://apicovid2019test.azurewebsites.net/
